### ISSUE TITLE
Error when running commands on MacOS Ventura with M1 chip

### ISSUE THREAD

**Issue by DjCrqss** [JohannLai/gptcli#11]
dj@DJs-MacBook-Pro .config % gptcli command `js files in the folder`                
Error: can't open files: No such file or directory
node:fs:589
  handleErrorFromBinding(ctx);
  ^

Error: EACCES: permission denied, open '/Users/dj/.config/gpt-cli/.gptrc'
    at Object.openSync (node:fs:589:3)
    at Object.readFileSync (node:fs:457:35)
    at Y (file:///opt/homebrew/lib/node_modules/@johannlai/gptcli/dist/cli.mjs:2:620)
    at D (file:///opt/homebrew/lib/node_modules/@johannlai/gptcli/dist/cli.mjs:2:868)
    at file:///opt/homebrew/lib/node_modules/@johannlai/gptcli/dist/cli.mjs:21:72 {
  errno: -13,
  syscall: 'open',
  code: 'EACCES',
  path: '/Users/dj/.config/gpt-cli/.gptrc'
}

**Comment by JohannLai** [comment]
I'm sorry for the problem, you can change the configuration with `vim ~/.config/gpt-cli/.gptrc`, I'll check the problem
