### ISSUE TITLE
Title: Error while running gptcli: fetch failed

### ISSUE THREAD

**Issue by sebastien-sq** [JohannLai/gptcli#20]
I encountered an error while using the gptcli project when trying to make a request. Here’s the error message I received:

`$ t? "hello wolrd"
⠋ AI is thinking ...Error: request openai error, fetch failed
C:\Users\Seb\AppData\Roaming\npm\node_modules\@johannlai\gptcli\node_modules\undici\index.js:112
        Error.captureStackTrace(err, this)
              ^

TypeError: fetch failed
    at fetch (C:\Users\Seb\AppData\Roaming\npm\node_modules\@johannlai\gptcli\node_modules\undici\index.js:112:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async y (file:///C:/Users/Seb/AppData/Roaming/npm/node_modules/@johannlai/gptcli/dist/loading-313601b9.js:1:244)
    at async l.run (file:///C:/Users/Seb/AppData/Roaming/npm/node_modules/@johannlai/gptcli/dist/jobs/gpt/createChatCompletion.js:1:546)
    at async D (file:///C:/Users/Seb/AppData/Roaming/npm/node_modules/@johannlai/gptcli/dist/cli.mjs:6:492) {
  cause: Error: getaddrinfo ENOTFOUND api.gptboxapp.com
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26) {
    errno: -3008,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'api.gptboxapp.com'
  }
}`

Observed Behavior
I received an error indicating that the request failed with the message getaddrinfo ENOTFOUND api.gptboxapp.com.
When I ping api.gptboxapp.com,

`$ ping api.gptboxapp.com
The Ping request could not find the host api.gptboxapp.com. Please check the name and try again..`

Is the api down ?

**Comment by akamalov** [comment]
I'd like to second this. It is broken. It is referencing `api.gptboxapp.com`, which does not exist.
