### ISSUE TITLE
Error: ENOENT: no such file or directory, open '/home/sterben/.config/gpt-cli/.gptrc'

### ISSUE THREAD

**Issue by Sterben667** [JohannLai/gptcli#5]
When i install gptcli, i have this issue : 
node:fs:600
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open '/home/<user>/.config/gpt-cli/.gptrc'
    at Object.openSync (node:fs:600:3)
    at Object.readFileSync (node:fs:468:35)
    at b (file:///usr/local/lib/node_modules/@johannlai/gptcli/dist/cli.mjs:2:390)
    at K (file:///usr/local/lib/node_modules/@johannlai/gptcli/dist/cli.mjs:2:494)
    at file:///usr/local/lib/node_modules/@johannlai/gptcli/dist/cli.mjs:16:230 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/<user>/.config/gpt-cli/.gptrc'
}

i fixed it with create gpt-cli dir in .config and .gptrc file. 

`mkdir ~/.config/gpt-cli && touch .config/gpt-cli/.gptrc`

**Comment by JohannLai** [comment]
hi @Sterben667 thanks for install it. 

what system are you using?

**Comment by DjCrqss** [comment]
I have the same problem. Latest version of MacOS with m1 chip
